name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Set up Go
      uses: actions/setup-go@v5
    - name: Set up air and golang-migrate
      run: |
        go install github.com/air-verse/air@latest
        go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
    - name: Set up PostgreSQL database
      uses: ikalnytskyi/action-setup-postgres@v7
      id: postgres
      with:
        database: plst4
    - name: Migrate PostgreSQL database
      run: env -u PGSERVICEFILE migrate -database "${{ steps.postgres.outputs.connection-uri }}?sslmode=disable" -path db/migrations up
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ steps.postgres.outputs.connection-uri }}" >> .env
        echo "MAIL_MODE=memorymail" >> .env
        echo "JWT_SECRET=secret" >> .env
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
